<?php

namespace StudentBundle\Repository;

/**
 * StudentRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRegistrationRepository extends \Doctrine\ORM\EntityRepository
{
}
