<?php

namespace UserBundle\Repository;

/**
 * AvatarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilePictureRepository extends \Doctrine\ORM\EntityRepository
{
}
