<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends AbstractUserRepository
{
    /**
     * Loads the user for the given username.
     *
     * This method must return null if the user is not found.
     *
     * @param string $username The username
     *
     * @return UserInterface|null
     */
    public function loadUserByUsername($username)
    {
        $user = $this->createQueryBuilder('u')
            ->where('s.barcode = :barcode')
            ->setParameter('barcode', $username)
            ->getQuery()
            ->getOneOrNullResult();


        return $user;
    }


    /**
     * @return EntityRepository
     */
    protected function getRepository()
    {
        return $this->_em->getRepository("UserBundle:Student");
    }
}
