<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserInterface;
use UserBundle\Entity\Student;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends AbstractUserRepository
{
    protected $alias = 's';

    /**
     * Loads the user for the given username.
     *
     * This method must return null if the user is not found.
     *
     * @param string $username The username
     *
     * @return UserInterface|null
     */
    public function loadUserByUsername($username)
    {
        $user = $this->createQueryBuilder('u')
            ->where('s.barcode = :barcode')
            ->setParameter('barcode', $username)
            ->getQuery()
            ->getOneOrNullResult();


        return $user;
    }


    /**
     * @return EntityRepository
     */
    protected function getRepository()
    {
        return $this->_em->getRepository("UserBundle:Student");
    }

    /**
     * @param int $number
     *
     * @return Student|null
     */
    public function findByNumber(int $number)
    {
        return $this->createQueryBuilder('s')
            ->where('s.number = :number')
            ->setParameter('number', $number)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     *
     * @param string $firstName
     * @param string $lastName
     *
     * @return null|Student
     */
    public function findByName(string $firstName, string $lastName)
    {
        return $this->createQueryBuilder('s')
            ->where('s.firstName = :firstName')
            ->andWhere('s.lastName = :lastName')
            ->setParameter('firstName', $firstName)
            ->setParameter('lastName', $lastName)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
