<?php

namespace CmsBundle\Repository;

use CoreBundle\Repository\AbstractRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends AbstractRepository
{
    protected $alias = 'p';

    /**
     * @param string $slug
     *
     * @return mixed
     */
    public function getHomepage(string $slug)
    {
        return $this->createQueryBuilder('p')
            ->where('p.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult();
    }

}
