<?php

namespace CourseBundle\Repository;

use CoreBundle\Repository\AbstractRepository;

/**
 * CourseContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseContentRepository extends AbstractRepository
{
    protected $alias = 'cc';
}
