<?php

namespace CourseBundle\Repository;

/**
 * CourseContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseContentRepository extends \Doctrine\ORM\EntityRepository
{
}
