<?php

namespace CourseBundle\Repository;

/**
 * ClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeClassRepository extends \Doctrine\ORM\EntityRepository
{
}
