<?php

namespace CourseBundle\Repository;

use CoreBundle\Repository\AbstractRepository;
use CourseBundle\Entity\GradeClass;

/**
 * ClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeClassRepository extends AbstractRepository
{
    protected $alias = 'gc';


    /**
     * @param int    $gradeName
     * @param string $sectionName
     *
     * @return GradeClass|null
     */
    public function findOneByGradeNameAndSectionName(int $gradeName, string $sectionName)
    {
        return $this->createQueryBuilder('gc')
            ->join('gc.grade', 'g')
            ->Where('g.grade = :gradeName')
            ->andWhere('gc.section = :sectionName')
            ->setParameter('sectionName', $sectionName)
            ->setParameter('gradeName', $gradeName)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
