<?php

namespace CourseBundle\Repository;

use CoreBundle\Repository\AbstractRepository;

/**
 * GradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeRepository extends AbstractRepository
{
    protected $alias = 'g';
}
