<?php

namespace CourseBundle\Repository;

use CoreBundle\Repository\AbstractRepository;

/**
 * ClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeClassRepository extends AbstractRepository
{
    protected $alias = 'gc';
}
