<?php

namespace CourseBundle\Repository;

use CoreBundle\Repository\AbstractRepository;
use CourseBundle\Entity\Grade;

/**
 * GradeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradeRepository extends AbstractRepository
{
    protected $alias = 'g';

    /**
     * @param int $grade
     *
     * @return Grade|null
     */
    public function findByGradeName(int $grade)
    {
        return $this->createQueryBuilder('g')
            ->where('g.grade = :grade')
            ->setParameter('grade', $grade)
            ->getQuery()
            ->getOneOrNullResult();
    }

}
