<?php

namespace CourseBundle\Repository;

use CoreBundle\Repository\AbstractRepository;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends AbstractRepository
{
    protected $alias = 'l';
}
